name: Ping server

on:
  schedule:
  - cron: "30 * 12 6 *"

jobs:
  ping:
    name: ping
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Ping server
      run: npm ci && npm run ping-server
